# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_position', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NewSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date_created')),
                ('location_details', models.TextField(blank=True, null=True)),
                ('charges', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='newslot',
            name='slot_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.NewSpace'),
        ),
    ]
