# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslot',
            name='slot_status',
            field=models.BooleanField(default=False),
        ),
    ]
